branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/ # regex

language: android

jdk:
  - oraclejdk8

before_install:
    - pip install --user codecov
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport

after_success:
  - ./gradlew coveralls
  - codecov

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository
